spring:
  application:
    name: pratice

  data:
    mongodb:
      uri: mongodb://root:root@localhost:20030/?authSource=admin
      database: chatting

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#  mvc:
#    static-path-pattern: "/static/**"

server:
  port: 8080

logging:
  level:
    root: info

rabbitmq:
  queue:
    name: chat.queue
  exchange:
    name: chat.exchange

# 채팅 경로
chat:
    path: http://localhost:8080